# Generated by Django 5.2 on 2025-05-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='instruction',
            new_name='instructions',
        ),
    ]
